emojiDB = {
	"joy":"😀😃😄😁🙂☺️😊",
	"laugh":"😁😂😆🤣",
	"sorrow":"😞😕😢😭😖😣🙁",
	"surprise":"🤯😯😱😧😮😨😲",
	"anger":"😤😠😡🤬😾👺",
	"no expression":"😐😶",
	"Baby":"👶",
	"Hand":"👍✌👌🖐🤘",
	"Cattle":"🐮🐄",
	"Cat":"🐱🐈😸😹😺😻😼😽😾😿🙀",
	"Dog":"🐶🐕🐩🐕‍🦺",
	"Mouse":"🐭🐁🐀",
	"Koala":"🐨",
	"Rabbit":"🐰🐇",
	"Hamster":"🐹",
	"Fox":"🦊",
	"Fish":"🐟🐠🐡",
	"Shark":"🦈",
	"Bear":"🐻",
	"Panda":"🐼",
	"Monkey":"🐵🐒🙊🙉🙈",
	"Gorilla":"🦍",
	"Turtle":"🐢",
	"Tiger":"🐯🐅",
	"Lion":"🦁",
	"Pig":"🐷🐖🐽🐗",
	"Boar":"🐗",
	"Goat":"🐐",
	"Frog":"🐸",
	"Chicken":"🐔🐓🐤🐥🐣",
	"Duck":"🦆",
	"Eagle":"🦅",
	"Owl":"🦉",
	"Bat":"🦇",
	"Penguin":"🐧",
	"Horse":"🐴🐎🏇🎠🦄",
	"Bee":"🐝",
	"Ant":"🐜",
	"Butterfly":"🦋",
	"Snail":"🐌",
	"Beetle":"🐞",
	"Scorpion":"🦂",
	"Primate":"🐵🐒🙊🙉🙈🦍🦧",
	"Dragon":"🐲🐉",
	"Sun":"☀🌞🔆🌅🌤",
	"Moon":"🌑🌚🌜🌛🌙",
	# "Flower":"🌷🌸🌹🌺🌼🥀💐🌻",
	"Rainbow":"🌈",
	"Snowflake":"❄",
	"Plant":"🌿🌱",
	"Heart":"❤🧡💛💚💙💜🖤",
	"Apple":"🍎🍏",
	"Banana":"🍌",
	"Pear":"🍐",
	"Lemon":"🍋",
	"Grape":"🍇",
	"Strawberry":"🍓",
	"Eggplant":"🍆",
	"Carrot":"🥕",
	"Corn":"🌽",
	"Pepper":"🌶",
	"Potato":"🥔",
	"Onion":"🧅",
	"Nut":"🌰🥜",	
	"Egg":"🥚🍳",
	"Bread":"🍞🥖",
	"Sandwich":"🥪",
	"Waffle":"🧇",
	"Meat":"🥩",
	"Bacon":"🥓",
	"Cheese":"🧀🍕",
	"French fries":"🍟",
	"Hot dog":"🌭",
	"Taco":"🌮",
	"Burrito":"🌯",
	"Popcorn":"🍿",
	"Salt":"🧂",
	"Lollipop":"🍭",
	"Melon":"🍈",
	"Watermelon":"🍉",
	"Pineapple":"🍍",
	"Coconut":"🥥",
	"Burger":"🍔",
	"Pizza":"🍕",
	"Tea":"🍵☕",
	"Football":"🏈🏉",
	"Soccer":"⚽",
	"Sports":"🏅",
	"Basketball":"🏀",
	"Table tennis racket":"🏓",
	"Award":"🏆",
	"Medal":"🥇🥈🥉🎖🏅",
	"Microphone":"🎤🎙",
	"Guitar":"🎸",
	"Music":"🎶🎵🎼",
	"Headphones":"🎧",
	"Corded phone":"📞☎",
	"Mobile phone":"📱",
	"Star":"🌟⭐🤩✨🌠💫",
	"Car":"🚗🚘",
	"Police car":"🚔🚓👮‍♂️👮‍♀️",
	"Robot":"🤖",
	"Pumpkin":"🎃",
	"Ghost":"👻",
	"Cucumber":"🥒",
	"Tomato":"🍅",
	"Lettuce":"🥬",
	"Rose":"🌹",
	"Soup":"🍲",
	"Calculator":"🧮",
	"Money":"💵💶💷💲💸",
	"Diamond":"💎",
	"Ring":"💍",
	"Bell":"🔔🛎",
	"Magnet":"🧲",
	"Compass":"🧭",
	"Bomb":"💣",
	"Coffin":"⚰",
	"Laptop":"💻",
	"Gun":"🔫",
	"Water":"💦💧🌊",
	"Fire":"🔥",
	"Planet":"🌎🌍🌏",
	"Umbrella":"☔☂🌂",
	"Beach":"🏖⛱",
	"Sea":"⛵",
	"Chair":"🪑",
	"Pill":"💊",
	"Virus":"🦠",
	"Bath":"🛀🛁",
	"Soap":"🧼",
	"Chemistry":"⚗🧪",
	"File":"📁📂🗃",
	"Scissors":"✂",
	"Paper":"📰📃📜📄",
	"Paperclip":"📎🖇",
	"Letter":"📨📩💌📧✉",
	"Mailbox":"📮📫📪📬📭",
	"Graph":"📈📉📊",
	"Waste container":"🗑",
	"Ruler":"📏📐",
	"Pin":"📌📍",
	"Beer":"🍺🍻",
	"Pen":"🖊✒🖋",
	"Pencil":"✏📝",
	"Tie":"👔",
	"Airplane":"✈️🛩",
	"Boat":"🚤⛵",
	"Canoe":"🛶",
	"Ship":"🚢🛳",
	"Sculpture":"🗿",
	"Traffic light":"🚦🚥",
	"Recycling":"♻",
	"House":"🏠🏡🏚🏘",
	"Building":"🏫🏢🏦🏨",
	"Factory":"🏭",
	"Painting":"🎨🖼",
	"Anchor":"⚓🔱",
	"Rocket":"🚀",
	"Astronaut":"👩‍🚀👨‍🚀",
	"Ambulance":"🚑",
	"Bus":"🚌🚇🚎🚍🚐",
	"Map":"🗺",
	"Leaf":"🍁🍂🍃",
	"Space":"🌌☄",
	"Oak":"🌳",
	"Palm tree":"🌴",
	"Pine":"🌲",
	"Brick":"🧱",
	"Dolphin":"🐬",
	"Flamingo":"🦩",
	"Dove":"🕊",
	"Mushroom":"🍄",
	"Lightning":"⚡🌩",
	"Cloud":"☁",
	"Tornado":"🌪",
	"Rain":"🌧☔⛈🌦",
	"Snow":"🌨⛄☃🏂",
	"Ice cream":"🍨🍦",
	"Avocado":"🥑",
	"Cherry":"🍒🌸",
	"Broccoli":"🥦",
	"Wine":"🍷",
	"Baseball":"⚾",
	"Cap":"🧢",
	"Dice":"🎲",
	"Piano":"🎹",
	"Dart":"🎯",
	"Scooter":"🛵🛴",
	"Firefighter":"🚒👩‍🚒👨‍🚒",
	"Ferris wheel":"🎡",
	"City":"🏙🌆",
	"Keyboard":"⌨",
	"Printer":"🖨",
	"CD":"💿📀💽",
	"Hammer":"🔨",
	"Wrench":"🔧",
	"Cigarette":"🚬",
	"Key":"🔑🗝",
	"Lock":"🔒🔓",
	"Calendar":"📅📆🗓",
	"Magnifying glass":"🔍🔎",
	"Microscope":"🔬",
	"Crayon":"🖍",
	"Book":"📚📕📗📘📙📔📖",
	"Door":"🚪",
	"Present":"🎁",
	"Box":"📦🗳",
	"Christmas":"🎅❄🤶",
	"Christmas tree":"🎄",
	"Chocolate":"🍫",
	"Bed":"🛌🛏",
	"Clock":"⏰⏱🕒🕰",
	"Watch":"⌚",
	"Card game":"🃏♦️♠️♥️♣️",
	"Flag":"🏴🏁🏳🚩",
	"Frame":"🖼",
	"Dynamite":"🧨",
	"Telescope":"🔭",
	"Sword":"⚔🤺",
	"Plug":"🔌",
	"Baloon":"🎈",
	"Confetti":"🎊🎉",
	"Light bulb":"💡",
	"Flashlight":"🔦",
	"Camera":"📷📸📹",
	"Parachute":"🪂"
}